name: 'files-action'
description: 'Upload files to Azure'
author: 'Vendanor'
branding:
  icon: file-text
  color: yellow

inputs:
  azure-token:
    required: true
    description: 'Your azure token'
  azure-account-name:
    required: false
    description: 'Azure account name'
    default: 'vnproductionstoragev2'
  salt:
    required: true
    description: 'Add some salt'
  input:
    required: true
    description: 'Source filename you want to upload'
  append-md5-hash:
    required: false
    description: 'Apply md5 hash at to target filename'
    default: true
  folder:
    required: false
    description: 'Subfolder in azure. Example "images/". No leading slash, but include trailing slash.'

outputs:
  filename:
    description: 'Uploaded filename'

runs:
  using: 'node12'
  main: 'dist/index.js'
